### ISSUE TITLE
SQL Backend

### ISSUE THREAD

**Issue by efruchter** [i3l/Critical#1]
The fake backend to the fake EHR

**Comment by PaulBernier** [comment]
I built a first version of an API to retrieve data. Example deployed here:
http://www.paulbernier.fr/critical_api/api/patient/132540/
http://www.paulbernier.fr/critical_api/api/patient/132540/stats/
http://www.paulbernier.fr/critical_api/api/patient/132540/stats/paco2

**Comment by efruchter** [comment]
Looks good! What hardware are you running it on?

**Comment by PaulBernier** [comment]
I have a friend who owns a dedicated server and he created a VM on it for me. I don't really know the hardware of his server nor the capacity of my VM (I use it only to host my git repositories and some small websites)
