### ISSUE TITLE
Google Charts?

### ISSUE THREAD

**Issue by efruchter** [i3l/Critical#2]
Is GC up to the task of rendering our data?

**Comment by davidmpark** [comment]
im looking through and the way they read the data is from creating table
something like [a,b,c,d]. they may be some variations on the format of data table they read to create charts but if you dump some of our data in google spreadsheet,
it can read the data and plot on their chart. it says google Spreadsheets support the google charts query language for sorting and filtering data. ill look into it a bit more

**Comment by davidmpark** [comment]
assuming most of data will be vital signs, we can create dump data into multiple spreadsheet then plot them in a line graph. other data like patient ino as well

**Comment by bmenn** [comment]
Do we want to mark the Visualization milestone closed or do we want more done for milestone?

**Comment by davidmpark** [comment]
besides vital signs and few of patient info, im not sure whatelse could be in. Ill work during the break to have some kind of prototype graph part.
